# Generated by Django 4.2.2 on 2023-06-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_slots',
            field=models.JSONField(blank=True),
        ),
    ]
