# Generated by Django 4.2.2 on 2023-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_slots',
            field=models.JSONField(),
        ),
    ]
